#!/usr/bin/env php
<?php
/**
 * Sample console script.
 *
 * Copy this file to your project (bin/console is recommended), change the paths
 * to app.php and run it by using "php bin/console".
 */
if (!defined('BASEDIR')) {
        define('BASEDIR', realpath(__DIR__ . '/'));
    }
set_time_limit(0);
error_reporting(0);
require_once BASEDIR . '/App/Bootstrap.php';
	
$bootstrap = new Bootstrap();


$app = $bootstrap->getapp();

if (!$app instanceof Silex\Application) {
    throw new LogicException(sprintf('The bootstrap file %s must return an instance of Silex\Application.', $bootstrapFilePath));
}
if (!isset($app['console'])) {
    throw new LogicException('The console service does not exist. Did you forget to register Knp\Provider\ConsoleServiceProvider ?');
}

$console = $app['console'];
//$console->add(new Activity($app));
//$console->add(new Command\PassHash($app));
$console->add(new Command\WebSocketServer($app));
$console->add(new Command\IpInfo($app));
$console->run();
