translation:
    locale_fallbacks:
        1: "en"
    locale: "en"

assets:
    assets.version: "v1"
    assets.version_format: "%s?version=%s"
    assets.named_packages:
        css:
            version: "css2"
            base_path: ""
        images:
            base_urls:
                1: "https://img.example.com"
                
parameters:
    #--- TimeZone: UTC, Europe/Kiev...
    timezone: UTC
    #--- Debug: true, false ---
    debug: false
    #--- Database parameters ---
    mysql_params:
        driver     : "mysql"
        host       : "localhost"
        database   : ""
        username   : ""
        password   : ""
        charset    : "utf8"
        collation  : "utf8_general_ci"
        prefix     : "sm_"
    redis_params:
        host: "127.0.0.1"
        port: 6379
        password: "redis@2017"
    #---------MonoLog-----------
    monolog:
        chanels:
            1: "sql"
            2: "debug"
        mailer:
            email: ""
            subject: "PHP error_log message"
            from: ""
    wss:
        AccessKey: ""
        SecretKey: ""
        region: "eu-west-2"
        service: "execute-api"
        stage: "production"
        idApi: ""
access_ip:
    1: "192.99.201.45"
   
anonymousRoute:
    1: "/authenticate/signin"
    2: "/authenticate/signup"
    3: "/authenticate/refreshtoken"
    4: "/socialoauth/facebook"
    5: "/socialoauth/google"
    6: "/socialoauth/linkedin"
    7: "/readme"
    8: "/authenticate/accesstoken"
    9: "/socialoauth/link"
    10: "/authenticate/app/firstlogin"
    11: "/authenticate/app/reload"
    12: "/plans/freecheckout"
    13: "/forgetpass/check"
    14: "/forgetpass/email"

anonymousUrlContain:
    1: '/^\/js/i'
    2: '/^\/css/i'
    3: '/^\/images/i'
    4: '/^\/Cache\/Compress/i'
    5: '/^\/Cache\/Images/i'
    
software:
    name: ""
    global_email: ""
    address: "68 King William St, London EC4N 7DZ"
    phone:
    fax:
    #--- Developer mail ---
    developer_mail: "dev@mail.com"
    
mail:
    smtp:    
        mail.host: mail.host.local
        mail.port: 25
        mail.username: ""
        mail.password: ""
        # ('tls', 'ssl', or null)
        mail.encryption: null
        # ('plain', 'login', 'cram-md5', or null)
        mail.auth_mode: null
        # Disabling Sending
        mail.disable_delivery:  true
    
webservice:
    view: "https://crm.smartysoftware.net/"
    crm: "https://apicrm.smartysoftware.net/"
    companyhouse: "https://apicompanyhouse.smartysoftware.net/"
    login: "https://oauth.smartysoftware.net/"
    setting: "https://setting.smartysoftware.net/"
    accounting: "https://acc.smartysoftware.net/"
    website: "https://www.smartysoftware.net/"
    