access_ip:
    1: "127.0.0.1"
anonymousRoute:
    1: "/signin"
    2: "/signup"
    3: "/device"
    4: "/signup/resend/verifyemail"
    5: "/verifyinvitecode"
    8: "/readme"
    
anonymousUrlContain:
    1: '/^\/js/i'
    2: '/^\/css/i'
    3: '/^\/images/i'
    4: '/^\/Cache\/Compress/i'
    5: '/^\/Cache\/Images/i'
    6: '/^\/error/i'
    7: '/^\/forget\/.*/i'
    8: '/^\/signup\/verify\/.*/i'
    9: '/^\/subdomain\/verify\/.*/i'
    11: '/^\/subdomain\/code\/.*/i'
    10: '/^\/subdomain\/getpicture\/.*/i'
    
uploadrestrictions:
    #5 Megabyte = 5242880 Byte
    maxsize: 5242880
    allowedtype:
        1: "jpg"
        2: "jpe"
        3: "jpeg"
        4: "gif"
        5: "png"
        6: "bmp"
        7: "tif"
        8: "tiff"
        9: "pdf"

MaximumRequest: 5