<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>You have been invited to join {{company_name}} Company.</title>
		<meta http-equiv="content-Type" content="text/html;charset=utf-8" />

		<style type="text/css">

			a:hover {color: #0088cc; text-decoration: underline !important;}
			a:active {color: #0088cc !important;}
			a:visited {color: #0088cc !important;}
			body {font-family:system,-apple-system,-webkit-system-font,SFNSText,'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif; }
			p {font-family:system,-apple-system,-webkit-system-font,SFNSText,'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif; }

			@media only screen and (max-width: 620px) {
				table[class="body"] .container {width: 90% !important; min-width: 400px;}
			}

			@media only screen and (max-device-width:514px) {
				table[class="body"] .container {width: 90% !important; min-width: 280px;}
				table[class="body"] .show-for-desktop {display: none !important;}
				table[class="body"] .show-for-small {display: inherit !important;}
				table[class="body"] .hide-for-desktop {display: inherit !important;}
				table[class="body"] .left-align-mobile {text-align: left !important;}
				table[class="body"] .content {padding-top: 12px !important; padding-bottom: 12px !important;}
			}

			@media only screen and (min-device-pixel-ratio : 2),
			only screen and (-webkit-min-device-pixel-ratio : 2) {
				img { visibility:hidden; }
				*[id=logo] { background:url('{{app.config.webservice.view}}images/logo-crm.png') no-repeat 0 0; -webkit-background-size:131px 27px; }
			}

		</style>

		<!--[if gte mso 9]>
		<style type="text/css">
			table,td,div,p {font-family:system,-apple-system,-webkit-system-font,"SFNSText","Segoe UI","Helvetica Neue",Helvetica,Arial,sans-serif; line-height:normal !important}
		</style>
		<![endif]-->
		<!--[if lte mso 7]>
		<style type="text/css">
		table,td,div,p {font-family:system,-apple-system,-webkit-system-font,"SFNSText","Segoe UI","Helvetica Neue",Helvetica,Arial,sans-serif; line-height:normal}
		</style>
		<![endif]-->

	</head>
	<body style="width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #333333; display: block; text-align: left; line-height: 1.6em; font-size: 16px; margin: 0 auto; padding: 0; font-weight: 300; font-family:system,-apple-system,-webkit-system-font,SFNSText,'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif;">

		<table class="body" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; height: 100%; width: 100%; padding: 0;">

			<tr style="vertical-align: top; text-align: left; padding: 0;" align="left">
				<td class="center" align="center" valign="top" style="border-collapse: collapse !important; vertical-align: top; text-align: center; padding: 0;">

					<center style="width: 100%;">

						<table class="container" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; width: 600px; margin: 0 auto; padding: 0;">

							<tr style="vertical-align: top; padding: 0;" align="left">
								<td style="border-collapse: collapse; vertical-align: top; padding: 0;" align="left" valign="top">

									<!-- Header Content -->
									<table class="header" style="border-spacing: 0; vertical-align: top; text-align: inherit; width: 100%; padding: 12px 0 9px; margin: 0; border-bottom: 1px solid #e9e9e9;">
										<tr style="vertical-align: top; text-align: left; padding: 0;" align="left">
											<td id="logo" width="131" height="27" align="left" valign="top">
												<a href="{{app.config.webservice.view}}">
													<img src="{{app.config.webservice.view}}images/logo-crm.png" width="131" alt="" border="0" align="left" />
												</a>
											</td>
										</tr>
									</table>

									<!-- Title Content -->


									<!-- Content -->
									<table class="content" style="border-spacing: 0; vertical-align: top; text-align: inherit; width: 100%; padding: 44px 0; margin: 0; border-bottom: 1px solid #e9e9e9;">
										<tr style="vertical-align: top; text-align: left; padding: 0;" align="left">
											<td style=" border-collapse: collapse !important; vertical-align: top; text-align: left; padding: 0;" align="left" valign="top">

												<p style="color: #333333; margin: 0; padding: 0; font-weight: 300; line-height: 1.6em; font-size: 16px; font-family:system,-apple-system,-webkit-system-font,SFNSText,'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif;">

													Dear Colleague,
												<br /><br />

													{{maker_name}} has invited you to join a company team, {{company_name}}, in the {{app.config.software.name}}. Please respond within 30 days. If you have any questions, contact {{maker_email}}.

												<br /><br />

												<a href="{{app.config.webservice.view}}system/invite/{{code}}" style="color:#0088cc; text-decoration: none;" class="smart-link">Accept&nbsp;invitation
													<img style="visibility:visible !important;" src="{{app.baseUrl}}images/Email/arrow_2x.gif" alt="" width="11" height="10" border="0">
												</a>
												<br /><br />
												Best regards,
												<br />
												{{app.config.software.name}} Relations

												</p>
											</td>
										</tr>
									</table>

									<!-- Footer Content -->
									<table class="footer" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; width: 100%; margin: 25px 0 10px; padding: 0;">
										<tr style="vertical-align: top; text-align: left; padding: 0;" align="left">
											<td style=" border-collapse: collapse; vertical-align: top; padding: 0;" align="left" valign="top">

												<p class="left-align-mobile" style="color: #999999; line-height: 1.6em; margin: 0; padding: 0; font-size: 9px; font-weight: 300; font-family:system,-apple-system,-webkit-system-font,SFNSText,'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif;">

													copyright &copy; {{ "now"|date("Y") }} {{app.config.software.name}}.  {{app.config.software.address}}.<br />

													<a href="{{app.config.webservice.view}}terms" style="color: #999999; text-decoration: none;">
														All Rights Reserved
													</a> / 
													<a href="{{app.config.webservice.view}}privacypolicy" style="color: #999999; text-decoration: none;">
														Privacy Policy
													</a>

												</p>
											</td>
										</tr>
									</table>

								</td>
							</tr>
						</table>

					</center>
				</td>
			</tr>
		</table>
	</body>
</html>